CREATE TABLE IF NOT EXISTS posts(
  id SERIAL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
  content VARCHAR(255) NOT NULL,
  thumbnail VARCHAR(255)
);